### Create new Bookmark
POST http://localhost:8080/api/bookmarks
Content-Type: application/json

{
  "title": "test",
  "url": "smac.ai"
}

### GET bookmark by id
GET http://localhost:8080/api/bookmarks/1

### GET all bookmarks
GET http://localhost:8080/api/bookmarks